spring.application.name: employee-api
server.port: 8111

# External server API base URL
employee:
  api:
    base-url: http://localhost:8112/api/v1/employee

# Logging configuration
logging:
  level:
    com.reliaquest.api: INFO
    reactor.netty.http.client: INFO
    io.github.resilience4j.retry: DEBUG
    springframework.web.reactive.function.client: INFO

# Resilience4j configuration
resilience4j:
  retry:
    instances:
      employeeApiRetry:
        max-attempts: 3
        wait-duration: 2s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
            - com.reliaquest.api.exceptions.TooManyRequestsException
            - com.reliaquest.api.exceptions.ExternalServiceException
            - java.io.IOException
            - org.springframework.web.reactive.function.client.WebClientRequestException

        ignore-exceptions:
            - com.reliaquest.api.exceptions.InvalidInputException
            - com.reliaquest.api.exceptions.EmployeeNotFoundException